version: '3'

services:

  # App Service
  app:
    build:
      context: .
      dockerfile: docker/app/dev/Dockerfile
    container_name: wallche_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
    container_name: wallche_api
    env_file: .env

  # Redis Service
  redis:
    image: "redis:alpine3.12"
    container_name: wallche_redis
    restart: unless-stopped
    networks:
      - backend
    env_file: .env
  db:
    image: mariadb:10.5.8-focal
    container_name: wallche_db
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretz
      MYSQL_DATABASE: wallche
      MYSQL_USER: wallche
      MYSQL_PASSWORD: wallchepass
    networks:
      - backend
    env_file: .env

networks:
  backend: